mydb <- dbConnect(RSQLite::SQLite(),"my-db.sqlite")
EMPLOYEE <- read.csv("~/Desktop/pstat 10/EMPLOYEE.txt")
DEPARTMENT <- read.csv("~/Desktop/pstat 10/DEPARTMENT.txt")
CUSTOMER <- read.csv("~/Desktop/pstat 10/CUSTOMER.txt")
SALES_ORDER <- read.csv("~/Desktop/pstat 10/SALES_ORDER.txt")
SALES_ORDER_LINE <- read.csv("~/Desktop/pstat 10/SALES_ORDER_LINE.txt")
INVOICES <- read.csv("~/Desktop/pstat 10/INVOICES.txt")
PRODUCT <- read.csv("~/Desktop/pstat 10/PRODUCT.txt")
EMPOLYEE_PHONE <- read.csv("~/Desktop/pstat 10/EMPLOYEE_PHONE.txt")
STOCK_TOTAL <- read.csv("~/Desktop/pstat 10/STOCK_TOTAL.txt")
dbWriteTable(mydb, "EMPLOYEE", EMPLOYEE)
dbWriteTable(mydb, "DEPARTMENT", DEPARTMENT)
dbWriteTable(mydb, "CUSTOMER", CUSTOMER)
dbWriteTable(mydb, "SALES_ORDER", SALES_ORDER)
dbWriteTable(mydb, "SALES_ORDER_LINE", SALES_ORDER_LINE)
dbWriteTable(mydb, "INVOICES", INVOICES)
dbWriteTable(mydb, "PRODUCT", PRODUCT)
dbWriteTable(mydb, "EMPOLYEE_PHONE", EMPOLYEE_PHONE)
dbWriteTable(mydb, "STOCK_TOTAL", STOCK_TOTAL)
dbListTables(mydb)
dbGetQuery(mydb, 'SELECT NAME FROM EMPLOYEE')
dbGetQuery(mydb, 'SELECT DISTINCT NAME FROM EMPLOYEE')
dbGetQuery(mydb, 'SELECT * FROM EMPLOYEE WHERE AGE > 31')
