PSTAT10db <- dbConnect(RSQLite::SQLite(), "PSTAT-db.sqlite")
dbGetQuery(PSTAT10db, 'SELECT * FROM STOCK_TOTAL INNER JOIN INVOICES 
           WHERE STOCK_TOTAL.PROD_NO = INVOICES.PROD_NO')

dbGetQuery(PSTAT10db, 'SELECT P.NAME AS ProductName, COLOR AS RequiredColor FROM CUSTOMER C, 
           SALES_ORDER_LINE O, SALES_ORDER S, PRODUCT P WHERE C.CUST_NO = S.CUST_NO 
           AND S.ORDER_NO = O.ORDER_NO AND O.PROD_NO = P.PROD_NO AND C.NAME IN ("ALEX", "CAROL")')

dbGetQuery(PSTAT10db, 'SELECT * FROM PRODUCT WHERE NAME = (SELECT NAME FROM PRODUCT WHERE PROD_NO = "p1")')

dbGetQuery(PSTAT10db, 'SELECT DEPT_NO FROM EMPLOYEE 
           WHERE EMP_NO IN (SELECT EMP_NO FROM EMPOLYEE_PHONE WHERE EXTENSION = "123")')

dbGetQuery(PSTAT10db, 'SELECT DEPT_NO FROM DEPARTMENT WHERE 
           NAME = "Accounts"')

dbGetQuery(PSTAT10db, 'SELECT DEPT_NO FROM DEPARTMENT WHERE NAME != "Stores"')
