PSTAT10db <- dbConnect(RSQLite::SQLite(), "PSTAT-db.sqlite")
dbGetQuery(PSTAT10db, 'SELECT SUM(QUANTITY) FROM STOCK_TOTAL')

dbGetQuery(PSTAT10db, 'SELECT PROD_NO FROM STOCK_TOTAL WHERE QUANTITY < 1000')

SALES_ORDER_LINE <- read.csv("~/Desktop/pstat 10/SALES_ORDER_LINE.txt")
dbWriteTable(PSTAT10db, "SALES_ORDER_LINE", SALES_ORDER_LINE)
dbWriteTable(PSTAT10db, "SALES_ORDER_LINE", SALES_ORDER_LINE, overwrite = TRUE)

dbGetQuery(PSTAT10db, 'SELECT NAME, MAX(AGE) FROM EMPLOYEE')

dbGetQuery(PSTAT10db, 'SELECT * FROM EMPLOYEE WHERE AGE > 50 AND NAME LIKE "%R%"')

dbGetQuery(PSTAT10db, 'SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_NO == "D3"')

dbGetQuery(PSTAT10db, 'SELECT COUNT(DEPT_NO) FROM DEPARTMENT')
